<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>ShellKrypt</ApplicationTitle>
    <ApplicationId>com.shellkrypt.app</ApplicationId>
    <ApplicationDisplayVersion>0.9.7</ApplicationDisplayVersion>
    <ApplicationVersion>17</ApplicationVersion>
    <SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <AndroidPackageFormat>aab</AndroidPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShellKrypt.Mobile\ShellKrypt.Mobile.csproj" />
  </ItemGroup>
</Project>
