using System.Collections.ObjectModel;
using Avalonia.Styling;

namespace ShellKrypt.UI.Shared.Theming;

public static class ShellKryptThemePalettes
{
    public const string DarkId = "dark";
    public const string LightId = "light";

    public static IReadOnlyDictionary<string, string> Dark { get; } =
        new ReadOnlyDictionary<string, string>(new Dictionary<string, string>
        {
            ["AppBackgroundBrush"] = "#121212",
            ["AppBackgroundSoftBrush"] = "#0b0b0c",
            ["CanvasBrush"] = "#121212",
            ["SurfaceBrush"] = "#1b1b1d",
            ["SurfaceRaisedBrush"] = "#242427",
            ["SurfaceElevatedBrush"] = "#2e2e32",
            ["SurfaceSunkenBrush"] = "#151517",
            ["SurfaceHoverBrush"] = "#38383d",
            ["SidebarBrush"] = "#18181a",
            ["BorderBrushSoft"] = "#334f4f56",
            ["BorderBrushStrong"] = "#66787882",
            ["WindowOutlineBrush"] = "#28282b",
            ["TextPrimaryBrush"] = "#f0f0f2",
            ["TextMutedBrush"] = "#aaaab2",
            ["TextDisabledBrush"] = "#74747d",
            ["TextInverseBrush"] = "#050505",
            ["TextSelectionBackgroundBrush"] = "#087f9c",
            ["TextSelectionForegroundBrush"] = "#ffffff",
            ["AccentBrush"] = "#00819a",
            ["AccentTextBrush"] = "#22c7e8",
            ["AccentHoverBrush"] = "#00a8c3",
            ["AccentPressedBrush"] = "#006d83",
            ["AccentMutedBrush"] = "#102f3a",
            ["AccentForegroundBrush"] = "#ffffff",
            ["SuccessBrush"] = "#9cd1c6",
            ["SuccessMutedBrush"] = "#174544",
            ["SuccessForegroundBrush"] = "#9cd1c6",
            ["WarningBrush"] = "#ffd1aa",
            ["WarningMutedBrush"] = "#3a3228",
            ["WarningForegroundBrush"] = "#ffd1aa",
            ["DangerBrush"] = "#ffb4ab",
            ["DangerMutedBrush"] = "#3a2426",
            ["DangerPanelBrush"] = "#261e1112",
            ["DangerBorderBrush"] = "#55ffb4ab",
            ["DangerForegroundBrush"] = "#050505",
            ["DangerHoverBrush"] = "#ff8f8f",
            ["InfoBrush"] = "#bacac5",
            ["InfoMutedBrush"] = "#2a2a2a",
            ["TableShellBrush"] = "#0b0b0c",
            ["TableHeaderBrush"] = "#1b1b1d",
            ["TableRowBrush"] = "#242427",
            ["TableRowHoverBrush"] = "#2e2e32",
            ["TableRowSelectedBrush"] = "#38383d",
            ["TableBorderBrush"] = "#1b1b1e",
            ["TableFooterBrush"] = "#1b1b1d",
            ["InputBackgroundBrush"] = "#0b0b0c",
            ["InputBorderBrush"] = "#334f4f56",
            ["InputHoverBorderBrush"] = "#66787882",
            ["InputFocusBorderBrush"] = "#22c7e8",
            ["FocusRingBrush"] = "#22c7e8",
            ["ModalCardBrush"] = "#1b1b1d",
            ["CardPreviewBackgroundBrush"] = "#102832",
            ["CardPreviewGradientStartColor"] = "#18566a",
            ["CardPreviewGradientEndColor"] = "#06141d",
            ["ModalBorderBrush"] = "#66787882",
            ["OverlayScrimBrush"] = "#b0000000",
            ["OverlaySoftScrimBrush"] = "#70000000",
            ["ResizeHitTestBrush"] = "#01000000",
            ["WatermarkBrush"] = "#0fffffff",
            ["QuoteBackgroundBrush"] = "#101918",
            ["HeroGlowPrimaryBrush"] = "#1800ffff",
            ["HeroGlowSecondaryBrush"] = "#101a4f47",
            ["CaptionButtonForegroundBrush"] = "#cccccc",
            ["CaptionButtonHoverBrush"] = "#2a2d2e",
            ["CaptionButtonHoverForegroundBrush"] = "#ffffff",
            ["CaptionButtonCloseHoverBrush"] = "#c42b1c",
            ["TypeWebBackgroundBrush"] = "#223b36",
            ["TypeWebForegroundBrush"] = "#9cd1c6",
            ["TypeCardBackgroundBrush"] = "#4a3827",
            ["TypeCardForegroundBrush"] = "#ffd1aa",
            ["TypeNoteBackgroundBrush"] = "#174544",
            ["TypeNoteForegroundBrush"] = "#57f1db",
            ["TypeAuthenticatorBackgroundBrush"] = "#1c3e4a",
            ["TypeAuthenticatorForegroundBrush"] = "#9fe8ff",
            ["TypeApiKeyBackgroundBrush"] = "#174544",
            ["TypeApiKeyForegroundBrush"] = "#57f1db",
            ["StrengthNoneBrush"] = "#7b8a87",
            ["StrengthWeakBrush"] = "#ffb4ab",
            ["StrengthFairBrush"] = "#ffd1aa",
            ["StrengthStrongBrush"] = "#2dd4bf"
        });

    public static IReadOnlyDictionary<string, string> Light { get; } =
        new ReadOnlyDictionary<string, string>(new Dictionary<string, string>
        {
            ["AppBackgroundBrush"] = "#f5f8fa",
            ["AppBackgroundSoftBrush"] = "#eaf0f3",
            ["CanvasBrush"] = "#f5f8fa",
            ["SurfaceBrush"] = "#ffffff",
            ["SurfaceRaisedBrush"] = "#f8fbfc",
            ["SurfaceElevatedBrush"] = "#edf3f6",
            ["SurfaceSunkenBrush"] = "#edf2f4",
            ["SurfaceHoverBrush"] = "#e3ecef",
            ["SidebarBrush"] = "#edf2f4",
            ["BorderBrushSoft"] = "#3377898f",
            ["BorderBrushStrong"] = "#6677898f",
            ["WindowOutlineBrush"] = "#d6e0e4",
            ["TextPrimaryBrush"] = "#172326",
            ["TextMutedBrush"] = "#54676e",
            ["TextDisabledBrush"] = "#788a90",
            ["TextInverseBrush"] = "#ffffff",
            ["TextSelectionBackgroundBrush"] = "#087f9c",
            ["TextSelectionForegroundBrush"] = "#ffffff",
            ["AccentBrush"] = "#00819a",
            ["AccentTextBrush"] = "#08758f",
            ["AccentHoverBrush"] = "#00a8c3",
            ["AccentPressedBrush"] = "#006d83",
            ["AccentMutedBrush"] = "#d8f1f6",
            ["AccentForegroundBrush"] = "#ffffff",
            ["SuccessBrush"] = "#16836d",
            ["SuccessMutedBrush"] = "#dff4ef",
            ["SuccessForegroundBrush"] = "#0f6f5d",
            ["WarningBrush"] = "#ad681c",
            ["WarningMutedBrush"] = "#fff0db",
            ["WarningForegroundBrush"] = "#7a4714",
            ["DangerBrush"] = "#b94d5a",
            ["DangerMutedBrush"] = "#fde7ea",
            ["DangerPanelBrush"] = "#fff1f3",
            ["DangerBorderBrush"] = "#66b94d5a",
            ["DangerForegroundBrush"] = "#ffffff",
            ["DangerHoverBrush"] = "#9f3e4b",
            ["InfoBrush"] = "#54676e",
            ["InfoMutedBrush"] = "#edf3f6",
            ["TableShellBrush"] = "#e9eff2",
            ["TableHeaderBrush"] = "#ffffff",
            ["TableRowBrush"] = "#f8fbfc",
            ["TableRowHoverBrush"] = "#edf3f6",
            ["TableRowSelectedBrush"] = "#e3ecef",
            ["TableBorderBrush"] = "#d5e0e4",
            ["TableFooterBrush"] = "#ffffff",
            ["InputBackgroundBrush"] = "#ffffff",
            ["InputBorderBrush"] = "#3377898f",
            ["InputHoverBorderBrush"] = "#6677898f",
            ["InputFocusBorderBrush"] = "#087f96",
            ["FocusRingBrush"] = "#087f96",
            ["ModalCardBrush"] = "#ffffff",
            ["CardPreviewBackgroundBrush"] = "#dceff4",
            ["CardPreviewGradientStartColor"] = "#e8fbfd",
            ["CardPreviewGradientEndColor"] = "#9bd4df",
            ["ModalBorderBrush"] = "#6677898f",
            ["OverlayScrimBrush"] = "#99000000",
            ["OverlaySoftScrimBrush"] = "#70000000",
            ["ResizeHitTestBrush"] = "#01000000",
            ["WatermarkBrush"] = "#16000000",
            ["QuoteBackgroundBrush"] = "#eef8fb",
            ["HeroGlowPrimaryBrush"] = "#180f9fbd",
            ["HeroGlowSecondaryBrush"] = "#18d8f1f6",
            ["CaptionButtonForegroundBrush"] = "#54676e",
            ["CaptionButtonHoverBrush"] = "#d6e0e4",
            ["CaptionButtonHoverForegroundBrush"] = "#172326",
            ["CaptionButtonCloseHoverBrush"] = "#c42b1c",
            ["TypeWebBackgroundBrush"] = "#dff4ef",
            ["TypeWebForegroundBrush"] = "#0f6f5d",
            ["TypeCardBackgroundBrush"] = "#fff0db",
            ["TypeCardForegroundBrush"] = "#7a4714",
            ["TypeNoteBackgroundBrush"] = "#d8f1f6",
            ["TypeNoteForegroundBrush"] = "#0a7f99",
            ["TypeAuthenticatorBackgroundBrush"] = "#e1f0ff",
            ["TypeAuthenticatorForegroundBrush"] = "#266986",
            ["TypeApiKeyBackgroundBrush"] = "#e6e8ff",
            ["TypeApiKeyForegroundBrush"] = "#4c58a8",
            ["StrengthNoneBrush"] = "#54676e",
            ["StrengthWeakBrush"] = "#b94d5a",
            ["StrengthFairBrush"] = "#ad681c",
            ["StrengthStrongBrush"] = "#0a7f99"
        });

    public static IReadOnlyList<ShellKryptThemeDefinition> All { get; } =
    [
        new(DarkId, "Dark", ThemeVariant.Dark, Dark),
        new(LightId, "Light", ThemeVariant.Light, Light)
    ];

    public static ShellKryptThemeDefinition Default => All[0];

    public static ShellKryptThemeDefinition GetById(string? id)
        => All.FirstOrDefault(theme => string.Equals(theme.Id, id, StringComparison.OrdinalIgnoreCase)) ?? Default;
}
